### ISSUE TITLE
ارور در برنامه drawfonts

### ISSUE THREAD

**Issue by nimafanniasl** [ekm507/araste-fonts#3]
```
'یـ' : '''
 
 
 
 
 
 
 
 
      .
    xMMM
    .MMM
 '',:MMM
;MMMMMMM
.kkxxo:
  :o;,o
 .WMNNMW
  .;  ;

''',
'ـ' : '''
Traceback (most recent call last):
  File "/tmp/araste-fonts/tools/./drawfont.py", line 67, in <module>
    print_glyph_block(character)
  File "/tmp/araste-fonts/tools/./drawfont.py", line 51, in print_glyph_block
    out = ocounto(oo)
  File "/tmp/araste-fonts/tools/./drawfont.py", line 30, in ocounto
    kk.append(ff[:i])
UnboundLocalError: local variable 'i' referenced before assignment
```

**Comment by ekm507** [comment]
نکتهٔ اول این که این چرا داره یک گلیف خالی رو ترسیم می‌کنه؟
حدس می‌زنم مال اون باشه. این اسکریپت‌ها بد نوشته شده‌اند و اصلاحشون سخته. پیشنهاد می‌کنم اون نویسه‌ای که باعث می‌شه این برنامه کار نکنه رو حذف کنی. یا این که به ادامهٔ برنامه اهمیت ندهی و خروجی رو تا جایی که چاپ کرده استفاده کنی!
باید اسکریپت‌های بهتری نوشته بشه و احتمالاً بخش‌هایی از اسکریپت‌های موجود یا همهٔ اون‌ها نیاز به بازنویسی داشته باشند.
